### ISSUE TITLE
is pg-native dependency needed?

### ISSUE THREAD

**Issue by larsthorup** [vitaly-t/pg-promise#488]
Doing `npm install pg-promise@8.2` gives me `Error: Can't find Python executable` (on Windows) while `npm install pg-promise@8.1` works just fine. Was the recent addition of pg-native as a dependency (https://github.com/vitaly-t/pg-promise/commit/d4b49e5422255c77f56fcf8b538cdd1c66db7c33) intentional?

**Comment by vitaly-t** [comment]
Oh dear lord, that was such a stupid mistake! I am removing it immediately!

**Comment by vitaly-t** [comment]
Fixed in [v8.2.1](https://github.com/vitaly-t/pg-promise/releases/tag/v.8.2.1).

**Comment by larsthorup** [comment]
Thanks for the quick fix! :)

**Comment by xxRockOnxx** [comment]
`yarn install pg-promise` installed `8.6.5` but I still have this issue.

is `pg-native` actually needed? I looked at the FAQ but it seems like it is optional.

Here's the log

```
ERROR  Failed to compile with 2 errors                                                                                                                                                                                                       friendly-errors 12:40:28

These dependencies were not found:                                                                                                                                                                                                            friendly-errors 12:40:28
                                                                                                                                                                                                                                              friendly-errors 12:40:28
* dns in ./node_modules/pg/lib/connection-parameters.js                                                                                                                                                                                       friendly-errors 12:40:28
* pg-native in ./node_modules/pg/lib/native/client.js                                                                                                                                                                                         friendly-errors 12:40:28
                                                                                                                                                                                                                                              friendly-errors 12:40:28
To install them, you can run: npm install --save dns pg-native 
```

**Comment by vitaly-t** [comment]
pg-native is not actively needed, if you do not specifically require it, via the `pgNative` option.
